name = "CellBuilder"
uuid = "b57aca3b-6d87-46ac-9d13-852a14eb0c4c"
authors = ["Ewout van der Veer <ewoutvanderveer@msn.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
